using System;
using System.ComponentModel;

namespace Assets.Enums
{
    [Serializable]
    public enum Tag
    {
        [Description("Halalit")] 
        HALALIT,
        [Description("Weapon")]
        WEAPON,
        [Description("Enemy")] 
        ENEMY,
        [Description("Shot")] 
        SHOT,
        [Description("KnockbackWave")]
        KNOCKBACK_WAVE,
        [Description("ItemsFactory")]
        ITEMS_FACTORY,
        [Description("Item")]
        ITEM,
        [Description("PickupClawShooter")]
        PICKUP_CLAW_SHOOTER,
        [Description("PickupClaw")] 
        PICKUP_CLAW,
        [Description("Asteroid")] 
        ASTEROID,
        [Description("InternalWorld")]
        INTERNAL_WORLD,
        [Description("ExternalWorld")]
        EXTERNAL_WORLD,
        [Description("TopEdge")]
        TOP_EDGE,
        [Description("BottomEdge")]
        BOTTOM_EDGE,
        [Description("LeftEdge")]
        LEFT_EDGE,
        [Description("RightEdge")]
        RIGHT_EDGE,
        [Description("BarBorder")]
        BAR_BORDEDR,
        [Description("BarFill")]
        BAR_FILL,
        [Description("BarIcon")]
        BAR_ICON,
        [Description("EnemyShot")]
        ENEMY_SHOT,
        [Description("Explosion")]
        EXPLOSION,
        [Description("MovementJoystick")]
        MOVEMENT_JOYSTICK,
        [Description("AttackJoystick")]
        ATTACK_JOYSTICK,
        [Description("Attacks")]
        ATTACKS,
        [Description("Explosive")]
        EXPLOSIVE,
        [Description("ExplosionShockWave")]
        EXPLOSION_SHOCK_WAVE,
        [Description("Valuable")]
        VALUABLE,
    }
}